version: "3"

services:
  hex:
    container_name: "hex"
    image: hex:latest
    build:
      dockerfile: Dockerfile
    command: bash -c "python3 -m http.server -d ./public/"
    volumes:
      - .:/app
    ports:
      - "8000:8000"