version: "3"

services:
  hex:
    container_name: hex
    image: hex:latest
    build:
      context: ./app
      dockerfile: Dockerfile
    command: bash -c "flask --app main run --port 5000 --host=0.0.0.0"
    ports:
      - "${APP_PRIVATE_HEX_PORT:-5000}"

  reverse-proxy-hex:
    # The official v2 Traefik image
    image: traefik:v2.10
    container_name: reverse-proxy-hex
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - '${APP_PUBLIC_HTTP_PORT:-80}:80'
      - '${APP_PUBLIC_HTTPS_PORT:-443}:443'
      - '${APP_PUBLIC_HTTPS_PORT:-443}:443/udp'
      # The Web UI (enabled by --api.insecure=true)
      - '${TRAEFIK_DASHBOARD_PORT:-8080}:8080'
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/:/etc/traefik:ro


volumes:
  node: