version: "3"

services:
  hex:
    container_name: "hex"
    image: hex:latest
    build:
      dockerfile: Dockerfile
    command: bash -c "flask --app main run --port 8000 --host=0.0.0.0"
    volumes:
      - node:/app/node_modules
      - .:/app
    ports:
      - "8000:8000"


volumes:
  node: