entryPoints:
  hex:
    address: ":443"

  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: hex
          scheme: https
          permanent: true

api:
  # Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true
  insecure: true

providers:
  file:
    filename: /etc/traefik/dynamic_conf.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true